apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ETXpNREV6TkRZMU5Gb1hEVE15TURNeU56RXpORFkxTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0hLCm1TbXQ0SERsUVQ1VTkzS3M1bjhST2U5czBjYTdHUnFZaEJKaDBQaFVqb2NZUzhFNXY3ZTdVSzJaRmFSRnFSKzUKbVRXR3hxVW5PMW85WjB5UVBlcExhc1I1ZjdRd2VMcXRuOUJXZ3I4a3l3OEdvMkxPdXd4YnN6cTFkUWhoOWl4ZAp1RS9POVhqeW9uZDdSVzdBRkxKWmViTXNHSGw4ZFdtci9zT0tFbDZJL2VDU2VPNC9xSDdGZlF5K05zcFo5VmhFCnNyOG9id3BkbVFwQUJxN2RiK01rVGpjTXo4Z0FBYzk2NTdxY3lZa2c0Ulo0TEdjUStITnVFelJqbFhhclZhZ0kKNVJZMHkxc1NZalBzUWFxb3o2WjNpRCt6cXpqbUZObnBCNUFmZ2pKRkR3UkcvK2JRTnZhSVFTUXU5WkpXZTZMeQo4MlhYN1NGRlJTQ1RjYS9URlYwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKT3NsNldCeWVNUHkxS3k4RFJlUnNBeWlPM1JNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBZHNHZng5RnZhK0hiUDdKVjlsUnZIK2wrc2J1UVcreHgybjIwcEVLRERYSElvdWxyWApURHlmdFlINHJidFVBODZsRllQVGpZR2ttKzJ4dno0SnR1aW00Vldya3NYekt2bEl6dWdoYU1iVlRYM0ZWdGtoCjlTNGlBRGhhU3QzdS9BMXZJYWdZWlA3cWtjVGJrRFFrQ1VpRnFwTklQUklObzdBWmpPY2lvTlNFaXRNR3h4TTIKc1JUUkx1UjM2WldpOXE0RjJWUDVaMEhjQWZRK1cwMVl0MTNqWlNRZzV5RllpNlczcnRWalNQd1FjNFJZVjhURgpJUDNVTzl1RTFJL1oxWUJHL3ZOQUNjc1JpNDNjdkt4UVVQdnlIT3hDWS9CYWJsR041QWpGTHBWQTlONm5OdHNvCmpzS1FDdHBRTHBXQ1l0T213dXQ5YWptRWZRTjdSNkRaWDJpTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://6F9934D5ECF52E08F0E570B7B9BEB24A.sk1.eu-west-1.eks.amazonaws.com
  name: aws-north.eu-west-1.eksctl.io
contexts:
- context:
    cluster: aws-north.eu-west-1.eksctl.io
    user: bmoussaud@vmware.com@aws-north.eu-west-1.eksctl.io
  name: bmoussaud@vmware.com@aws-north.eu-west-1.eksctl.io
current-context: bmoussaud@vmware.com@aws-north.eu-west-1.eksctl.io
kind: Config
preferences: {}
users:
- name: bmoussaud@vmware.com@aws-north.eu-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - aws-north
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-west-1
      provideClusterInfo: false
