# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: ${NODE_TYPE}
    desiredCapacity: ${NODE_NUMBER}

