kind: Service
apiVersion: v1
metadata:
  name: az-srvclb-ngnx
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-loadbalancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      imagePullSecrets:
      - name: azure-registry
      containers:
      - name: nginx
        image: "akseutap6registry.azurecr.io/library/nginx"
      
