apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-3
  namespace: dev
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.20.8---vmware.1-tkg.2
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.20.8---vmware.1-tkg.2
    
  settings:
      network:
        cni:
          name: antrea
        trust:
          additionalTrustedCAs:
            - name: BenoitHarbor3
              data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGa1RDQ0EzbWdBd0lCQWdJVUtuU1AyWEhabU8waGZLdlBESGVYWnFjZUFod3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3VVRFTE1Ba0dBMVVFQmhNQ1EwNHhEREFLQmdOVkJBZ01BMUJGU3pFUU1BNEdBMVVFQnd3SFFtVnBTbWx1DQpaekVQTUEwR0ExVUVDZ3dHVmsxM1lYSmxNUkV3RHdZRFZRUUREQWhJWVhKaWIzSkRRVEFlRncweU16QTVNRFV4DQpOVFExTWpkYUZ3MHpNekE1TURJeE5UUTFNamRhTUZZeEN6QUpCZ05WQkFZVEFrTk9NUXd3Q2dZRFZRUUlEQU5RDQpSVXN4RURBT0JnTlZCQWNNQjBKbGFVcHBibWN4RHpBTkJnTlZCQW9NQmxaTmQyRnlaVEVXTUJRR0ExVUVBd3dODQpNVEF1TWpFMExqRTRNaTQ1TWpDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTER6DQpPUGxHRkw0eVBsdjdzdHIxUUp0cURjRGxQbjNwSGRXWWx0SyswY3RqblRNU2xST3Q5WGFhak4xdlVSMk92Ujc5DQpNTjFraVUzcmxUenh3ZHE4TjA4Q2ZZSEMzV0x1djZvcTR0VmZFOHNJMEtiN2svbzJRL0l4T3owNzBObWpOcmZXDQorbEg5dDVFN25IS2U3N3FvOWNKcHdDMGJybXhnZVgrOFBOUytKb3NmRGdXL0JLMGlLbUQ4dVlhbytkcDkraU52DQpsS3E1RFJFTzFnZVJnS25KbVRFS0dZVHRJUmErOXEyQjlUYVU1MFZFbXlCL0lxWVN6bXdmUVQxMWRqWUlOWjRGDQpjcy9vYXdpcFNCTFd2czByUzRZck1tekZ6dVpJc3FHUnNISWNaMFFNS1I2UnU3emh3N3YzY093Y2hmNitsQkxjDQpSV2d4cDFkc1FFNS9ORFEvQ1FzdjRRODlIVDFYempVUVo0d2tOUzVoR0t6VG4vNHhTckZBYWttOXlhZ1RnUkZ6DQpxNkZZZkgwZDByTGY0RjB2NCtEenoxMVd5cjUwNERURHRxTkVXNGpYbGJKeTdwZGFsb1lnc1E2akRUVnR1alFjDQpZcXlPQ0c1U0tYMjNubTlINzlQZXFuYXQ2a2lScC9VcXB5Q202K1NHbGpkcnJzWDVpNVNlbVo4MkdaRUh0aTVXDQpQV3BQT1dIVW95UHJaTldoZXdmenA0ZFhyS28rRWhqcWtBWEt2QlZHWmZXN2RpOVVZMU5mMUlSRkdScHNPMmlJDQo0alIyNk81QXo3T3BsUFdHbEt0MFFReVcyRDY3UDRzbXAzZGxlU0ZKeEFuQWZsMFBmSFlGbkxPbC9NSDA1NE9VDQpDa3RZNkdFbjBEV3R6NzBrK1NyekxOTWMyU0Z3WUJNTW1Xd0tTWTZIQWdNQkFBR2pYREJhTUJnR0ExVWRFUVFSDQpNQStDRFRFd0xqSXhOQzR4T0RJdU9USXdIUVlEVlIwT0JCWUVGTU1nRGZsNGFQZlg0em5JNWlMbnJ3d0J6VUgwDQpNQjhHQTFVZEl3UVlNQmFBRkdyZENLY2ZGVUp6MXc3NnBiVHUyR2hxaGIzZU1BMEdDU3FHU0liM0RRRUJDd1VBDQpBNElDQVFBNlJjVnJiV1R4M09nOEgwMTNTdjE0MTNjcjAyWU1qREQwMk5hay9qL0hiYUFQVjlHY1M5bnVSSnJPDQpVVXVSalNHem1qckdidEN0RFR6S2g4eGluajRjSHdjM1h3UXlmV1M0dDBoNkRPVnhwcVk2NXdiMTV3Q2JWQUdjDQpiWVNET0d0MTBlQ2hSQnhRY3JxR2xpZVhQNFB0TjlsYkJwQUFtSndONS94U216bHRuWWozSEhEKzRNb1ZKcCt1DQptbW1uWnllRmRDV0xNalhQdHR5MXdCQndHNDJjNHdieGhVT0VDN01vZzBadnozb01SWUxRcDUrUit5RGdLV0liDQowZzNWaFFVLzZqLzZPTlJCNVEvdzF5Ni9aa012cWVMaUdrSXZ5RUx6WjAxUGRrNm5lQ2xoYUxrWXdTa1hSS3RBDQpWRHAvZFdjZFhoVG5rb2FvS29aSnRTbnpORVV1VWNReHdjUUdYaW5rK1RjVXlCb3p0RURta3g0NmpRV1pPcFczDQpzSVRUSElhSUFOcE5vZkowWWJBblAvNm9nYTJDQk1WemFSTXZ2ZklheWtYRFdzMVpPbmtRa2I4Q0JSYlhnRDdvDQpxb1g5aWdGRGxPQzB3OUNCT1RSUXdKSzlPdXdzZE50RW9XbTh1dFk1d1ZxNUxuTmhRa242T1JaUDhoLy9XTXA5DQo2dlVHTUFqelpFanFhWFRSMDgxMWRWeklPMW1iTXFaQmhacnlteUMwd29hYnl4bytUbUM2WWs2WVFWREtiV1J1DQpCQVJzYW5BdDEwZ2JsYWNqMHNSWUY2RVFKb1F1MyszNGNrRTRKdGRMOVA1T0Y2cmdZZ3hwK1FqME13SHJtbEtTDQo2R3BGVnNDcmRoSUdYdnZRNWQ3S2lkQUl5aGJmRHJYMTVWNFJ0WjY5QXljdjMyWElmZz09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
