apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: prod01
  namespace: bmoussaud
spec: 
  distribution:
    version: v1.18
  topology:
    controlPlane:
      count: 3
      class: best-effort-small
      storageClass: tanzu
    workers:
      count: 10
      class: best-effort-small
      storageClass: tanzu

