apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-1
  namespace: dev
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1  
  settings:
        network:
          cni:
            name: antrea
          trust:
            additionalTrustedCAs:
              - name: harborpoc.h2o-4-18157.h2o.vmware.com
                data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ2ekNDQTZlZ0F3SUJBZ0lVUi9sYzUxZUltbXNIR2dOZHB1c1VlU1ZDMk00d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VURUxNQWtHQTFVRUJoTUNRMDR4RERBS0JnTlZCQWdNQTFCRlN6RVFNQTRHQTFVRUJ3d0hRbVZwU21sdQpaekVQTUEwR0ExVUVDZ3dHVmsxM1lYSmxNUkV3RHdZRFZRUUREQWhJWVhKaWIzSkRRVEFlRncweU16QTVNRFl4Ck1qRTRNRGxhRncwek16QTVNRE14TWpFNE1EbGFNRzB4Q3pBSkJnTlZCQVlUQWtOT01Rd3dDZ1lEVlFRSURBTlEKUlVzeEVEQU9CZ05WQkFjTUIwSmxhVXBwYm1jeER6QU5CZ05WQkFvTUJsWk5kMkZ5WlRFdE1Dc0dBMVVFQXd3awphR0Z5WW05eWNHOWpMbWd5YnkwMExURTRNVFUzTG1neWJ5NTJiWGRoY21VdVkyOXRNSUlDSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFyNC81blYwSHIyYm1Da1F1Q09KamdkWkloTUw3NE4yTUcwdzkKNGRabzE1c29WTmRPUmF0SG5QWUdvbU8yTndpQVl2Yzk2UWw1NXVDZ0lsSHh5ZnVsNVRaak5mSCt1TjJ3Ny9MNQo5c0VNa1dja0h2d1BzbmQzc3IzS29pWGRVMXUwOXhESEc3cEZKWVF6dEphdGd4SDRuejJsTnZ3dHByZVVwRW9SCldmdWFJWVg5c3JCNGVXZ0VqelpibDNTbWNIT2tNNTV5enFCQmJGRzdmUTBwME1YTVRJTlVWRHZJSlFlWnFwNDEKajFzQmNEa1hBMjgrRmptQ1pOT1JZK0tSUmtCQnJ0NGtJVU56cmFmbFV2RitIcmdoWHRhejVsMnI0dEU1ZWY1SwplUWQwVDMvSmhyRWIwQ2NoVGppUEZBQUxoV1lyUkpCV2JEMDFMdGxPR1pQVGZrdnpITktTZVhROWlvdWhRQXl2CldldStuRU1VZjZRYzVYWElNdXZ3SGwwanVZaXh3QXkya3RtY3FxbGhGakxuQVZRRHJiakt1a2hBZzl0eUI4dzYKTE1zU0RjS2ZSS0pWNmxNNytPTTB4ZHg4NGFLemVJU000bTBZMlhxZmE5N29pUGJCRFJQOVFWUjAxMXpLLzEyRQp4TW5aUmpaN0N5QmxKRUdWK0g4YmpBbUU1R0h4bDJBUi81OEZ0dVpWRnREdEhwdmxYME5XVHpzZHAraTJJVHdyClFDOE1rdkhJazBOaGtOVGI0WkoyVjJsV0xOaERhME1hQlJTL0VSS29zWUlkZk1nV3cwZy84RksxTE5Bd1ZyVWcKSUR0amk3K0FrTGZLNkQxa2ZxdXg3SlVJNU15MjJFcHVHNEFJSnRFaWl3TWxDZXEzc1ZYSGZUdGlobDhQdTc2RApsd2hJaGVVQ0F3RUFBYU56TUhFd0x3WURWUjBSQkNnd0pvSWthR0Z5WW05eWNHOWpMbWd5YnkwMExURTRNVFUzCkxtZ3lieTUyYlhkaGNtVXVZMjl0TUIwR0ExVWREZ1FXQkJTYzlaZ1NPVTRvcEFCQ0JDTFgrajUxMzNmell6QWYKQmdOVkhTTUVHREFXZ0JUT2loelp2SEhzeDJQekdGbStXSldSbDlMTEN6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBZ0VBeFpINVdUaFJKZmxyRTdBd282NGdwMk80MTRvVHdCTzY4eHg0Vm1PYW4yWlBZUFlnc2o4eFVLZ3ZZOWpoCkdpbHNsLytQekduMnoyWkkrdUF1TnlhY2cwSDdhR1NKRS92VjFScFFwK0NpL3VrZUdFTDRsZFlKdzBHWGI4cloKaThyRVBXT003aVJNSVE0SWVUdU41UnpoemtheU1IUksrY0VXalE5Tkx2L0tEdjBDNi9wZEswQXVxUmFCc1VWNApVTlVMZEE1Y2NlN2FGL1UxamRFWlJPN0hSa0hvLzZNZStVclRmMWdQbHhFbEZzbnFhQWgrNTkvdkpXSVJDVnRuCnhCL1NJSmduaTZ1UUxkYXBXL0M5dGJ6bFduVTAxMXdwR05Wc2grVkhDaFhiQWJyTnFMQ29KVE1tOWNXcE9zaGkKMHU2b3kxQXo4YlRUMUdBcXluSEMxamRiSGJ4TW95U1FwWkM4R2xYWmpxS0xHeHJ0MWVwYm9PaURwMld2WjFQOQp6SUNaamF4VENycndWVUF6TXBpZnVFbk10eHdadTVEU0w5RGp3bTF3cW95cE8vZ0RKVjFmYWVOa2srVzl4MEdoCnhEZUp5MFh0Vy9XU0tTdDhyTDAwTmJtbjhzNEFDUkd5MWx1Y0dtdG9KVmszQ2pEaDlMYm5WTG5FTWJoaElZdTkKbVUwNUVlNndqN2MydmttbHZoRHBva3RkeEpsL0krV0hid3gwYnhGQU9rVmIwcTRHVmJMMUFSd2hDMklDcUFLLwpCbW8zTkQxVTZsTXYwRG9EaFFQT2lVQkM3b3czMTloV3J5NmduUEkvaUxjbFNDZFN4dWxkL25ZcFdxTm5VNzVXCnN5ZlZEQmpEdk9lcGJ2M0wwUVpMWk03UlRFbk8zRkdhWVBwVjBHUXB4N2xGUlkwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
