apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-3
  namespace: dev
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: best-effort-medium
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1  
