kind: Service
apiVersion: v1
metadata:
  name: srvclb-whoami
spec:
  selector:
    app: hello
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
#kubectl create secret docker-registry regcred  --docker-username=bmoussaud --docker-password=dckr_pat_1qwNLCQ7k85nCN1zQdfcv96BdSg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: containous/whoami
          imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred

