export TKG_IMAGE_REPO="projects.registry.vmware.com/tkg"
export TKG_CUSTOM_IMAGE_REPOSITORY=${INSTALL_REGISTRY_HOSTNAME}
#export TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE="LS0t[...]tLS0tLQ=="
export TKG_BOM_IMAGE_TAG="v1.5.4"

