---
apiVersion: v1
kind: Namespace
metadata:
  name: smoketest 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: smoketest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: smoketest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kuard
  namespace: smoketest
  labels:
    app: kuard
spec:
  backend:
    serviceName: kuard
    servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kuard-vh
  namespace: smoketest
  labels:
    app: kuard
spec:
  rules:
  - host: kuard.smoke.test
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80
