AZURE_CLIENT_ID: <encoded:MzFlNDJkYzktNWIxYS00MDhiLWEyYzQtM2UxZDg3MTFhNjRl>
AZURE_CLIENT_SECRET: <encoded:M25QOFF+MUVlSlRvNE5DMkh6Z2J2ZmRfb1c3aTJTelZCb3dsTmJxTg==>
AZURE_CONTROL_PLANE_MACHINE_TYPE: Standard_D4s_v3
AZURE_CONTROL_PLANE_SUBNET_CIDR: 10.0.0.0/24
AZURE_CONTROL_PLANE_SUBNET_NAME: tce-mgt-ctrl-vnet
AZURE_ENABLE_PRIVATE_CLUSTER: ""
AZURE_ENVIRONMENT: AzurePublicCloud
AZURE_FRONTEND_PRIVATE_IP: ""
AZURE_LOCATION: germanywestcentral
AZURE_NODE_MACHINE_TYPE: Standard_D4s_v3
AZURE_NODE_SUBNET_CIDR: 10.0.1.0/24
AZURE_NODE_SUBNET_NAME: tce-mgt-worker-vnet
AZURE_RESOURCE_GROUP: tce-azure-benoit
AZURE_SSH_PUBLIC_KEY_B64: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFEMEVkRGZGTjdNNGlrWjc2UWtya0RSNUFaTFhSMzA2RGd2VlVxTXV4T1FMaVJrdGxHSGFueWNjQ0haUEFKYVp2aVZPeGZMTTRqWks2R3ZNaGt4ck1zU1pZYWdFZVp3UEs4MldKZW9mVk9XdDJLeDJCdDZKRk50MkRIRUZvTEpSdG1MN3kzZ2NydE14K3FWcGlnQ05sMlNlbCttY01YRFhaQnRlUFVhLzlncFdGRmRRK2lTejg1UG1wT0NyZW1wczNSZk5uWWdxM2J1bXFSNVN1YlJSV3VHS3N4d0tPOXNqVjl3VFVubTJlS1JDZ01lbjRxMDllZFF5alJVOS9YWHhITDlCSkxIOXhORVd1U2xwN2xncmpIZTFVTFJwTDVaMUVZVE8vT3Q1R1JGOFhUNlJDWlVaejIyZDVaT0ZtTVVnNlVSckwzeXR5S0drY1ZQOW4yMWZsTmpXWFdOSUs2dnVUWEY1TGdyUUJ1dHpJbnMxanNUVnI3SjgvVkJ2dnFseDVpQnpOeXFmZWhVMDUxNnZWNitKVkhTY2QwYnpMRWZsWVhFcFRaQTJRRlJ0QlQ2L3FqVFoyTUlNbVdQcDNRZUFLQmlMcHJ5NldCWGswUEg1MzFUSzlQeFpzcEIyNFpkckdEUmwxTDhSVTV3WmIxQ0RuUnYvb0xneEg0Qm1ndUtPSnhSa3RpckdHNFJFdVg1MEdtVUU2b0lHUjk5YUtTVUUweCsxRXEyWjk0am5ZOU9LbTRmMytzdzgvOThWTk80aFVnb0VVT2svMmNMbHlsTGgvbDRHQ0xWeCtKazRacEo5Lyt3SVNubGM0NHpYRERJaWtXVkdSZHZtVHNDL1dYQlFQT3NxVUVXdWNjYTZRZWE3cWhmaHQ1cHhSSWNNY0JEQjcyWXN5NS9yeldxZ1E9PSBibW91c3NhdWRAbXl0YW56dWNvbW11bml0eWVkaXRpb24uY29tCg==
AZURE_SUBSCRIPTION_ID: cbca10bb-6ddc-45bd-8f18-c17d1dd1003f
AZURE_TENANT_ID: b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0
AZURE_VNET_CIDR: 10.0.0.0/16
AZURE_VNET_NAME: tce-mgt-vnet
AZURE_VNET_RESOURCE_GROUP: tce-azure-benoit
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tce-mgt-cluster
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "true"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: azure
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: ubuntu
OS_VERSION: "20.04"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
