apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  labels:
    name: frontendpvc1
spec:
  storageClassName: vc01cl01-t0compute
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

